[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
  cmd = "cd backend && npm ci"

[phases.build]
  cmd = "cd backend && npx prisma generate"

[phases.start]
  cmd = "cd backend && npm start"
